
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <SignAssembly>False</SignAssembly>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MarkdownSnippets.MsBuild" PrivateAssets="all" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="Argon" />
    <PackageReference Include="DiffEngine" />
    <PackageReference Include="EmptyFiles" />
    <PackageReference Include="SimpleInfoName" />
    <PackageReference Include="Verify" />
    <ProjectReference Include="..\Verify.ImageHash\Verify.ImageHash.csproj" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <PackageReference Include="ProjectFiles" PrivateAssets="all" />

    <None Update="sample.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
